ALTER TABLE blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE feeds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Feeds are publicly readable" ON feeds
    FOR SELECT USING (true);
